### ISSUE TITLE
Crash on option overrideMaterials=true

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#103]
Since 1.0.43 (not sure), if i enabling `B:overrideMaterials=true`, game crashes on startup with error:

```py
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Evolution (tconevo)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Trait to "amber": Trait "thundering" was already registered by Unknown
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
	at slimeknights.tconstruct.library.TinkerRegistry.checkMaterialTrait(TinkerRegistry.java:307)
	at slimeknights.tconstruct.library.materials.Material.addTrait(Material.java:278)
	at slimeknights.tconstruct.library.materials.Material.addTrait(Material.java:270)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialTrait(TinkerRegistry.java:281)
	at xyz.phanta.tconevo.handler.MaterialOverrideHandler.lambda$null$1(MaterialOverrideHandler.java:196)
	at com.google.common.collect.AbstractMapBasedMultimap.lambda$null$2(AbstractMapBasedMultimap.java:1279)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.google.common.collect.AbstractMapBasedMultimap.lambda$forEach$3(AbstractMapBasedMultimap.java:1279)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at com.google.common.collect.AbstractMapBasedMultimap.forEach(AbstractMapBasedMultimap.java:1278)
	at xyz.phanta.tconevo.handler.MaterialOverrideHandler.lambda$handleTraitInheritance$2(MaterialOverrideHandler.java:193)
	at java.util.Map.forEach(Map.java:630)
	at xyz.phanta.tconevo.handler.MaterialOverrideHandler.handleTraitInheritance(MaterialOverrideHandler.java:188)
	at xyz.phanta.tconevo.CommonProxy.onImcReceived(CommonProxy.java:156)
	at xyz.phanta.tconevo.TconEvoMod.onImcReceived(TconEvoMod.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

[Crashed debug.log](https://github.com/phantamanta44/tinkers-evolution/files/6703959/debug-1.log.gz)
[Normal debug.log with option set to "false"](https://github.com/phantamanta44/tinkers-evolution/files/6703967/debug-working.zip)

**Comment by phantamanta44** [comment]
should be fixed in 1.0.44
