### ISSUE TITLE
Crash on startup: Redstone Repository 2.0

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#114]
Recent update of [Redstone Repository Revolved](https://www.curseforge.com/minecraft/mc-mods/redstone-repository-revolved) now crashing game on startup.

```sass
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Evolution (tconevo)
Caused by: java.lang.NoClassDefFoundError: thundr/redstonerepository/items/baubles/ItemCapacitorAmulet
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at xyz.phanta.tconevo.integration.IntegrationManager.injectHooks(IntegrationManager.java:38)
	at xyz.phanta.tconevo.CommonProxy.onPreInit(CommonProxy.java:51)
	at xyz.phanta.tconevo.client.ClientProxy.onPreInit(ClientProxy.java:39)
	at xyz.phanta.tconevo.TconEvoMod.onPreInit(TconEvoMod.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

TConevo version: `1.0.44`
Redstone Repository cersion: `2.0.0`

**Comment by 23KiaraMinecraft** [comment]
I had this crash as well.

**Comment by phantamanta44** [comment]
yeah, sorry about that. i'm kinda busy right now, but i'll fix it when i can

**Comment by 23KiaraMinecraft** [comment]
Okay.

**Comment by lerokko** [comment]
Also had this error not sure if it helps but I leave the full Crash here (Also 1.4.0-dev still works for me FYI)

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Evolution (tconevo)
Caused by: java.lang.NoClassDefFoundError: thundr/redstonerepository/items/baubles/ItemCapacitorAmulet
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at xyz.phanta.tconevo.integration.IntegrationManager.injectHooks(IntegrationManager.java:38)
    at xyz.phanta.tconevo.CommonProxy.onPreInit(CommonProxy.java:51)
    at xyz.phanta.tconevo.client.ClientProxy.onPreInit(ClientProxy.java:39)
    at xyz.phanta.tconevo.TconEvoMod.onPreInit(TconEvoMod.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thundr.redstonerepository.items.baubles.ItemCapacitorAmulet
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 46 more
Caused by: java.lang.NullPointerException

```

**Comment by 23KiaraMinecraft** [comment]
I see this has not been touched on for a while. Maybe someone can create a pull request or something?
