### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by xANoyU** [phantamanta44/tinkers-evolution#122]
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/9274380/debug.log)

please help me. I don't understand what the problem is😔

**Comment by phantamanta44** [comment]
that file is empty! maybe try uploading it to pastebin or something like that?

**Comment by xANoyU** [comment]
> 那个文件是空的！也许尝试将其上传到 pastebin 或类似的东西？

[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/9274381/debug.log)

sorry, I uploaded it again
because the content is almost circular, I only intercepted part of it

`	at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:575) ~[ForgeHooks.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1041) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:817) ~[oq.class:?]
	at xyz.phanta.tconevo.handler.EnergyShieldHandler.onEntityAttacked(EnergyShieldHandler.java:97) ~[EnergyShieldHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1284_EnergyShieldHandler_onEntityAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-6eb82ffe]`

**Comment by xANoyU** [comment]
origin log file is full of errors, with a size of 173mb

**Comment by phantamanta44** [comment]
whoops, i think it's related to a rounding error that i overlooked; i'm kinda surprised it's never happened to anyone until now. i'll get around to fixing it...... eventually, but probably don't use draconic armour for the time being
