### ISSUE TITLE
Cannot load modifier-model

### ISSUE THREAD

**Issue by Keaft** [phantamanta44/tinkers-evolution#147]
I'm getting a bunch of "Cannot load modifier-model" errors through a FileNotFoundException.
They start around line 3343: [latest.log](https://github.com/phantamanta44/tinkers-evolution/files/14833321/latest.log)

illusivesoulworks/constructsarmory#108 is the only other place I've seen this error.

Here is a snippet of one of the errors:
```
[01:45:21] [Client thread/ERROR]: Cannot load modifier-model conarm:models/item/modifiers/tconevo.draconic_shield_capacity_armor
java.io.FileNotFoundException: conarm:models/item/modifiers/tconevo.draconic_shield_capacity_armor.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at slimeknights.tconstruct.library.client.model.ModelHelper.getReaderForResource(ModelHelper.java:79) ~[ModelHelper.class:?]
	at slimeknights.tconstruct.library.client.model.ModelHelper.getReaderForResource(ModelHelper.java:74) ~[ModelHelper.class:?]
	at slimeknights.tconstruct.library.client.model.ModelHelper.loadTexturesFromJson(ModelHelper.java:84) ~[ModelHelper.class:?]
	at slimeknights.tconstruct.library.client.model.ModifierModelLoader.loadFilesIntoCache(ModifierModelLoader.java:150) [ModifierModelLoader.class:?]
	at slimeknights.tconstruct.library.client.model.ModifierModelLoader.loadModel(ModifierModelLoader.java:78) [ModifierModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) [ModelLoaderRegistry.class:?]
	at c4.conarm.client.utils.ArmorModelLoader.loadModel(ArmorModelLoader.java:153) [ArmorModelLoader.class:?]
```

Do those files need to generate? If so do I need to refresh it somehow?

**Comment by phantamanta44** [comment]
No, the modifiers just do not currently have any models. There shouldn't be any impact on gameplay
